name: version
on:
  pull_request_target:
jobs:
  changelog:
    name: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Version updated
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: version.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
